### ISSUE TITLE
 friends-api.js怎么没了

### ISSUE THREAD

**Issue by jkjoy** [Fgaoxing/blog-cdn#1]
https://cdn.jsdelivr.net/gh/Fgaoxing/blog-cdn@main/source/js/friends-api.js

**Comment by Fgaoxing** [comment]
[Qexo/Qexo #357](https://github.com/Qexo/Qexo/discussions/357)

**Comment by Fgaoxing** [comment]
@jkjoy

**Comment by jkjoy** [comment]
> @jkjoy

谢谢!~不过这个API为何获取不到呢
