### ISSUE TITLE
vlts友链异常

### ISSUE THREAD

**Issue by qystudio0** [Fgaoxing/blog-cdn#1]
适配vlts新版的工作有进展吗

**Comment by Fgaoxing** [comment]
没有，尽快吧

**Comment by Fgaoxing** [comment]
我在解析https://github.com/volantis-x/hexo-theme-volantis/blob/dev/layout/friends.ejs文件

**Comment by Fgaoxing** [comment]
找了半天没啥问题，不知道为啥

**Comment by Fgaoxing** [comment]
class都一样啊

**Comment by qystudio0** [comment]
别看这个，看标签的，tag的文件夹

**Comment by Fgaoxing** [comment]
给班级水了个登录，https://fenghuang.vercel.app/，所以我都没看到

**Comment by Fgaoxing** [comment]
抱歉，我去问了，回没回话呐

**Comment by Fgaoxing** [comment]
> 别看这个，看标签的，tag的文件夹,我是按照friend改的！

**Comment by Fgaoxing** [comment]
你加上
```
layout: friends # 必须
```
试试

**Comment by Fgaoxing** [comment]
@qystudio0

**Comment by Fgaoxing** [comment]
@qystudio0 ok吗？

**Comment by qystudio0** [comment]
明天有空试试吧，谢谢

**Comment by qystudio0** [comment]
可以了，需要添加
> layout: friends # 必须
