### ISSUE TITLE
添加友链提交vlts版

### ISSUE THREAD

**Issue by qystudio0** [Fgaoxing/blog-cdn#2]
随便添加友链提交vlts专供版，适配vlts message

**Comment by qystudio0** [comment]
单独写一个js，把弹窗部分写成vlts的message

**Comment by Fgaoxing** [comment]
有亿点小麻烦，先搁置吧

**Comment by qystudio0** [comment]
给我权限我有空改改

**Comment by Fgaoxing** [comment]
你pr即可

**Comment by qystudio0** [comment]
OK

**Comment by qystudio0** [comment]
你适配下暗黑模式，51我改弹窗

**Comment by Fgaoxing** [comment]
@qystudio0 我会尽快

**Comment by qystudio0** [comment]
vlts通知适配完成https://github.com/qystudio0/cdn/blob/main/js/friends/ask_friend.js
如果你的样式更新可以提交到我这
地址: https://npm.elemecdn.com/qycdn/js/friends/ask_friend.js

**Comment by Fgaoxing** [comment]
@qystudio0 你可以去Qexo库申请添加https://github.com/Qexo/Qexo/discussions/new
